2018-12-29 10:46:02,859 error: multiprocessing_and_logging.py func1 ERROR 18423 this is test for error
2018-12-29 10:46:02,859 error: multiprocessing_and_logging.py func1 ERROR 18425 this is test for error
2018-12-29 10:46:02,859 error: multiprocessing_and_logging.py func1 ERROR 18426 this is test for error
2018-12-29 10:46:02,859 error: multiprocessing_and_logging.py func1 ERROR 18424 this is test for error
2018-12-29 10:46:02,859 error: multiprocessing_and_logging.py func1 ERROR 18422 this is test for error
